name: CI Day 2 Practice

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Step 1
        run: echo "ðŸš€ CI PIPELINE STARTED"

      - name: Step 2
        run: ls

      - name: Step 3
        run: echo "About to FAIL"

      - name: Step 4
        run: exit 1
